### ISSUE TITLE
Allow `enable_new` to be a function?

### ISSUE THREAD

**Issue by lougreenwood** [otavioschwanck/telescope-alternate.nvim#12]
I'm using the addon in a mono repo containing multiple projects, all of the projects are in the same language and using the same framework, so generally speaking the same alternate config file works for all of the mono repo projects.

However, a subset of the projects have additional requirements, specifically, one of the projects is a UI design system. Components in this design system share the same alternate file config as the other mono repo projects, but additionally they can have a `storybookJS` file.

I'd like to have a general config for all components across all of the projects in the mono repo, but only in the "design system" project do I want to show the prompt to create one of these additional "storybookJS" files.

So my thinking was that maybe the `enable_new` option could also accept a callback function, which would receive the full path of the matched pattern so we can check if the path is in a project which allows/expects these files to be created.

**Comment by otavioschwanck** [comment]
Implemented at 30711b87aea861172605a17aeb5603b202ade55b

**Comment by lougreenwood** [comment]
Nice, I was going to try this out myself, but thanks for implementing it!
