### ISSUE TITLE
Allow configuring Telescope mappings & layout

### ISSUE THREAD

**Issue by lougreenwood** [otavioschwanck/telescope-alternate.nvim#15]
I'd like to override the mapping for `<CR>` when viewing alternate files (I want to always open in a split) and also configure the layout strategy / theme used by the picker.

Because this is a telescope extension, it doesn't seem possible. I tried the following to set the config for the picker provided by the extension, but it also didn't seem to work:

```lua
{
 defaults = {
        mappings = {
          i = {
            ["<CR>"] = actions.select_tab,
            ["<C-b>"] = actions.select_default,
            ["<C-_>"] = actions.select_horizontal,
            ["<C-Bslash>"] = actions.select_vertical,
          },
        },
      },
      pickers = {
        alternate_file = {
          mappings = {
            i = {
              ["<CR>"] = actions.select_horizontal,
            }
          }
        }
      }
}
```

**Comment by otavioschwanck** [comment]
> I'd like to override the mapping for `<CR>` when viewing alternate files (I want to always open in a split) and also configure the layout strategy / theme used by the picker.
> 
> Because this is a telescope extension, it doesn't seem possible. I tried the following to set the config for the picker provided by the extension, but it also didn't seem to work:
> 
> ```lua
> {
>  defaults = {
>         mappings = {
>           i = {
>             ["<CR>"] = actions.select_tab,
>             ["<C-b>"] = actions.select_default,
>             ["<C-_>"] = actions.select_horizontal,
>             ["<C-Bslash>"] = actions.select_vertical,
>           },
>         },
>       },
>       pickers = {
>         alternate_file = {
>           mappings = {
>             i = {
>               ["<CR>"] = actions.select_horizontal,
>             }
>           }
>         }
>       }
> }
> ```

I will do this weekend

**Comment by otavioschwanck** [comment]
Its, done.  On setup, just add: 

```
    telescope_mappings = { -- Change the telescope mappings
      i = {
        open_current = '<CR>',
        open_horizontal = '<C-s>',
        open_vertical = '<C-v>',
        open_tab = '<C-t>',
      },
      n = {
        open_current = '<CR>',
        open_horizontal = '<C-s>',
        open_vertical = '<C-v>',
        open_tab = '<C-t>',
      }
    }
```
