### ISSUE TITLE
Consider supporting vim.regex in addition to Lua patterns

### ISSUE THREAD

**Issue by mlen** [otavioschwanck/telescope-alternate.nvim#17]
The common pattern when working on Go code is that the test files and implementation files are stored in the same folder. The alternate file of `foo.go` would be `foo_test.go`. I could define the mappings as below, but that means that whenever I look up the alternate file for `foo_test.go`, an entry for `foo_test_test.go` would show up in addition to `foo.go`.

```
{
  pattern = '(.*)/(.*).go',
  targets = {
    { template = '[1]/[2]_test.go', label = 'Test' },
  },
},
{
  pattern = '(.*)/(.*)_test.go',
  targets = {
    { template = '[1]/[2].go', label = 'Definition', enable_new = false },
  },
},
```

One way to solve this issue would be to expose an option to use a regexp engine that supports negative lookaheads, which IIUC are not supported by currently used `string.match`.

**Comment by otavioschwanck** [comment]
not planned
