### ISSUE TITLE
Register setup hook in telescope extensions

### ISSUE THREAD

**Issue by asmodeus812** [otavioschwanck/telescope-alternate.nvim#3]
Hi, it would be great if you could add a setup hook when the extension is registered to telescope, such as this one here - https://github.com/FeiyouG/command_center.nvim/blob/main/lua/telescope/_extensions/command_center.lua#L200

**Comment by otavioschwanck** [comment]
> Hi, it would be great if you could add a setup hook when the extension is registered to telescope, such as this one here - https://github.com/FeiyouG/command_center.nvim/blob/main/lua/telescope/_extensions/command_center.lua#L200

The setup is just to save the mappings, i didn't understand why to put on the telescope extension.  How the user should define their mappings in this way?  

A PR is welcome!

**Comment by asmodeus812** [comment]
Telescope provides an internal way to call the plugin specific setup method - the telescope config has the **extensions**, property which contains a table / map of configs for of each extension, telescope then calls the setup hook of each loaded extension with it's config - instead of having to do it separately in another file it's all controlled by telescope, makes sense since its a telescope extension which can't really exist in isolation on its own. All telescope extensions are providing that setup hook, it is literally this one line from the link above.

**Comment by otavioschwanck** [comment]
> Telescope provides an internal way to call the plugin specific setup method - the telescope config has the **extensions**, property which contains a table / map of configs for of each extension, telescope then calls the setup hook of each loaded extension with it's config - instead of having to do it separately in another file it's all controlled by telescope, makes sense since its a telescope extension which can't really exist in isolation on its own. All telescope extensions are providing that setup hook, it is literally this one line from the link above.

Implemented on last update!  See the README to see how to do on telescope setup.

Thanks!
