### ISSUE TITLE
Is it possible to do per-project settings?

### ISSUE THREAD

**Issue by turboladen** [otavioschwanck/telescope-alternate.nvim#8]
I realize this is probably an edge case, but I thought I'd ask in case there was some interest... I'm in the middle of a huge porting project, where I'm taking a web app that is a single Rails + Ember.js app and splitting it to two separate apps in the same repo. Without getting into details, the gist of my process has been to:

1. Split the app to `backend/` and `frontend/` dirs, where `backend/` contains the unchanged old app (so I can refer to it while porting), and `frontend/` contains the from-scratch new Ember app.
2. Setting up `frontend/` with standard Ember alternate mappings is easy-peasy, but I'd _also_ like to be able to set alternates to the originating files in `backend/`.

I realize I could do this using the normal plugin setup method, but it seems like it'd be nice to be able to specify this specifically for this project, since it's a bit atypical.

Either way, thanks for making the plugin--it's great!

**Comment by otavioschwanck** [comment]
You can create your custom verification:

when loading your config, verify if cwd is one project, execute one mappings, or else, execute another.

Exemple:

```
project_a = { ...mappings here }
project_any_here = { ...mappings here }

if vim.fn.getcwd() == '/Path/to/project_a' then
  require('telescope-alternate').setup(project_a)
else
  require('telescope-alternate').setup(project_any_here)
end

```

Or you can create vim functions to call the setup and switch anytime.

**Comment by turboladen** [comment]
Ah, perfect! Thanks!
