### ISSUE TITLE
Alternates in mapping paths?

### ISSUE THREAD

**Issue by lougreenwood** [otavioschwanck/telescope-alternate.nvim#9]
Hi, great addon! I'm using [this fork](https://github.com/iofusion/telescope-alternate.nvim) to allow me to use the addon in EmberJS projects.

One issue i've hit is that in Ember, sometimes a file may live in 2 locations (either `/app/` or `/addon/`) - they have the same path after this fragment.

I was hoping that my mapping could look like this `/(app|addon)/...`, but it seems that Lua matching doesn't offer this syntax and it would need something more complex like lua regex.

Is this something you've considered?

Thanks for the great addon - hopefully I can use it to replace `projectionist` in a modern nvim workflow!

**Comment by otavioschwanck** [comment]
Hi!  Thanks for you issue.

You can use lua regexp on the pattern like that:

```

require('telescope-alternate').setup({
  mappings = {
    { pattern = '([app|spec]+)/services/(.*)_services/(.*).rb', targets = {
      { template = '[1]/contracts/[2]_contracts/[3].rb', label = 'Contract' }
    } }, -- will go to app/contracts or spec/contracts depending on the base file
  }
})

```

EDIT:  About the addon, you can create a PR with ember.JS support for this project.

Just add in lua/telescope-alternate/presets.lua the ember key.

**Comment by lougreenwood** [comment]
Thanks, and to clarify, I didn't create that addon, but AFAIK the author does plan on upstreaming their fork once it is stable.

IIUC it extends `telescope-alternate` to allow switching between multiple alternates for a given file (i.e in `Ember` a `route`, `controller` and `template` & `acceptance test` are all related as a family and switching between each is necessary).

**Comment by otavioschwanck** [comment]
> Thanks, and to clarify, I didn't create that addon, but AFAIK the author does plan on upstreaming their fork once it is stable.
> 
> IIUC it extends `telescope-alternate` to allow switching between multiple alternates for a given file (i.e in `Ember` a `route`, `controller` and `template` & `acceptance test` are all related as a family and switching between each is necessary).

awesome!

**Comment by lougreenwood** [comment]
> Hi! Thanks for you issue.
> 
> You can use lua regexp on the pattern like that:
> 
> ```
> 
> require('telescope-alternate').setup({
>   mappings = {
>     { pattern = '([app|spec]+)/services/(.*)_services/(.*).rb', targets = {
>       { template = '[1]/contracts/[2]_contracts/[3].rb', label = 'Contract' }
>     } }, -- will go to app/contracts or spec/contracts depending on the base file
>   }
> })
> ```
> 

I'm trying to improve my pattern to get the part of the path before the `/app` part of the file path (this is because I'm working in a mono repo, so when I start my pattern with `[app|addon]+` `telescope-alternate` seems to disregard the beginning part of the file path and the patterns don't find existing files).

So I've been reading up on Lua pattern matching, and whilst `([app|addon]+)` seems to work with `telescope-alternate`, I can't see it documented anywhere and I keep finding things like this:

```
Limitations of Lua patterns

Especially if you're used to other languages with regular expressions, you might expect to be able to do stuff like this:

'(foo)+' 
'(foo|bar)' 

Unfortunately Lua patterns do not support this, only single characters can be repeated or chosen between, not sub-patterns or strings. The solution is to either use multiple patterns and write some custom logic, use a regular expression library like lrexlib or Lua PCRE, or use LPeg [[3]](http://www.inf.puc-rio.br/~roberto/lpeg/). LPeg is a powerful text parsing library for Lua based on Parsing Expression Grammar [[4]](https://en.wikipedia.org/wiki/Parsing_expression_grammar). It offers functions to create and combine patterns in Lua code, and also a language somewhat like Lua patterns or regular expressions to conveniently create small parsers.
```
http://lua-users.org/wiki/PatternsTutorial

So my question is - is there some other library being used to extend Lua pattern matching? I don't see `nvim` adding anything like that (other than `vim.regex`).

Specifically, given the following file path

`packages/my-project/app/component/thing.hbs`

I'm trying to match everything before `app` (or `addon`), using something like the following but I can't find any way to get it to work:

```lua
"([(.+)][^app|addon])"
```

**Comment by lougreenwood** [comment]
Or maybe an alternate & more robust solution to the mono repo problem is to make sure that, internally, the output of `:pwd` is always at the front of the template string?

**Comment by lougreenwood** [comment]
Turns out that what I actually need is simply just `(.-)([app|addon]+)`, but there's a bug in `utils normalize_path` which breaks `-` char in pattern brackets. I'll put up a PR later which fixes that bug.

Edit: [PR](https://github.com/otavioschwanck/telescope-alternate.nvim/pull/13)
